app = "trackr-backend"
primary_region = "sjc"

[build]
dockerfile = "./Dockerfile"

[env]
DATABASE_URL = "sqlite:///data/trackr.db"

[[mounts]]
source = "trackr_data"
destination = "/app/data"

[[services]]
internal_port = 9696
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[http_service]
internal_port = 9696
